[theme]

# Primary accent for interactive elements
primaryColor="#2E34DA"

# Background color for the main content area
backgroundColor="#9BA2AC"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor="#686C71"

# Color used for almost all text
textColor="#2E34DA"



# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"
[runner]
fasrRerun = true
[server]
maxUploadSize = 50
[browser]
gatherUsageStats = false
